const express = require('express')
const router = express.Router()
const adminControllerauth = require('../../Controller/admin/adminControllerauth')
const costomerController = require('../../Controller/admin/costomerController')
const categoyController = require('../../Controller/admin/categoryController')

router.get('/login', adminControllerauth.loadsign)
router.post('/login',adminControllerauth.login) 
router.get('/dashboard',adminControllerauth.loaddashboard)
router.get('/logout',adminControllerauth.logout)
router.get('/users',costomerController.loadUsers)
router.get('/userprofile/:id',costomerController.loadProfile)
router.post('/updateuser/:id',costomerController.profile)
router.patch('/toggle-user-status/:id',costomerController.block)
router.get('/categories',categoyController.loadcategories)
router.post('/addCategory',categoyController.addcategory)
router.get('/addcategories',categoyController.loadaddcategory)
router.post('/addCategoryOffer',categoyController.addcategoryOffer)
router.post('/removeCategoryOfffer',categoyController.removecategoryoffer)
router.get("/listcategory",categoyController.getlistcategory)
router.get("/unlistcategory",categoyController.getunlistcategory)

module.exports = router 